<a href="https://colab.research.google.com/github/hipparagiaishwarya2130-lang/datascience/blob/main/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#label encoding
import pandas as pd
#scikit-learn is a library
#preprocessing is a module
from sklearn.preprocessing import LabelEncoder
#labelencoder is a class has already inbuilt methods and members

In [6]:
df=pd.DataFrame({
    'Product':['Watch','Mouse','stove','shoe','stove','Mouse','Watch','shoe'],
    'subjects':['sql','Sql','Testing','genai','Genai','Testing','Testing','genai'],
    'objects':['marker','Duster','Duster','Marker','Pen','Duster','Pencil','Pen']

})
df
#DataFrame-understands only dict-constructor that creates dataframe

  Product subjects objects
0   Watch      sql  marker
1   Mouse      Sql  Duster
2   stove  Testing  Duster
3    shoe    genai  Marker
4   stove    Genai     Pen
5   Mouse  Testing  Duster
6   Watch  Testing  Pencil
7    shoe    genai     Pen

In [7]:
df

  Product subjects objects
0   Watch      sql  marker
1   Mouse      Sql  Duster
2   stove  Testing  Duster
3    shoe    genai  Marker
4   stove    Genai     Pen
5   Mouse  Testing  Duster
6   Watch  Testing  Pencil
7    shoe    genai     Pen

In [9]:
df['Product'].unique()
df['subjects'].unique()
df['objects'].unique()

array(['marker', 'Duster', 'Marker', 'Pen', 'Pencil'], dtype=object)

In [10]:
le= LabelEncoder()

In [11]:
#fit_transform- METHOD IN LABELENCODER
#transform- transforms mapped data into output
#.fit- will identify unique values-sorts amd maps

df['Product']= le.fit_transform(df['Product'])
df['subjects']=le.fit_transform(df['subjects'])
df['objects']=le.fit_transform(df['objects'])
df
#overwriting in original column

   Product  subjects  objects
0        1         4        4
1        0         1        0
2        3         2        0
3        2         3        1
4        3         0        2
5        0         2        0
6        1         2        3
7        2         3        2