<a href="https://colab.research.google.com/github/hipparagiaishwarya2130-lang/datascience/blob/main/Feature_Scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

FEATURE SCALING-

In [ ]:
#Standardisation
import pandas as pd
from sklearn.preprocessing import StandardScaler
df=pd.DataFrame({'grams':[2,3,4,5],'price':[200,500,800,1200]})
ss=StandardScaler()
#fit-learning data,calculating mean,devitaion done by fit
#transform-tranforming or reflecting it to original data
df_scaled=ss.fit_transform(df)
df_scaled

array([[-1.34164079, -1.28390102],
       [-0.4472136 , -0.47301616],
       [ 0.4472136 ,  0.33786869],
       [ 1.34164079,  1.41904849]])

In [ ]:
df2=pd.DataFrame(df_scaled,columns=df.columns)
df2

      grams     price
0 -1.341641 -1.283901
1 -0.447214 -0.473016
2  0.447214  0.337869
3  1.341641  1.419048

In [ ]:
#Standardisation
import pandas as pd
from sklearn.preprocessing import StandardScaler
df1=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')
ss1=StandardScaler()
n= df1.select_dtypes(include=['number']).columns
df1_numeric=df1[n]
df_scaled1=ss1.fit_transform(df1_numeric)
df_scaled1=pd.DataFrame(df_scaled1,columns=df1_numeric.columns)
df_scaled1

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years
0,-1.714126,-1.462863,-0.882040,-0.341235,-0.411165,1.788917,-0.147412
1,-1.714048,0.971113,1.220423,1.713436,-0.411165,1.788917,-0.147412
2,-1.695488,2.593763,1.420657,0.343655,-0.411165,1.788917,-0.147412
3,-1.712775,0.971113,0.439508,1.028546,-0.411165,1.788917,-0.147412
4,-1.712042,-1.462863,-0.841993,-0.341235,-0.411165,1.788917,-0.147412
...,...,...,...,...,...,...,...
14994,1.630149,-1.462863,-1.002181,-0.341235,-0.411165,1.788917,-0.147412
14995,1.630265,-1.462863,-0.821970,-0.341235,-0.411165,1.788917,-0.147412
14996,1.630496,-1.462863,-1.162368,-0.341235,-0.411165,1.788917,-0.147412
14997,1.630574,1.782438,1.580845,0.343655,-0.411165,1.788917,-0.147412
14998,1.630689,-1.462863,-0.862016,-0.341235,-0.411165,1.788917,-0.147412

In [1]:
#minmax scaler
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
df1=pd.DataFrame({'height':[160,154,148],'weight':[47,52,62]})
mm=MinMaxScaler()
M=mm.fit_transform(df1)
M=pd.DataFrame(M,columns=df1.columns)
M

   height    weight
0     1.0  0.000000
1     0.5  0.333333
2     0.0  1.000000

In [2]:
#minmax scaler
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
df2=pd.DataFrame({'score_py':[144,113,122],'score_sql':[66,89,45]})
mm1=MinMaxScaler()
M=mm1.fit_transform(df2)
M=pd.DataFrame(M,columns=df2.columns)
M

   score_py  score_sql
0  1.000000   0.477273
1  0.000000   1.000000
2  0.290323   0.000000

In [3]:
#normalizer
import pandas as pd
from sklearn.preprocessing import Normalizer
df3=pd.DataFrame({'height':[160,154,148],'weight':[47,52,62]})
mm2=Normalizer()
M=mm2.fit_transform(df3)
M=pd.DataFrame(M,columns=df3.columns)
M

     height    weight
0  0.959461  0.281842
1  0.947446  0.319917
2  0.922338  0.386385

In [4]:
#task---standard scaler
import pandas as pd
from sklearn.preprocessing import StandardScaler
df1 = pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv ')
n = df1.select_dtypes(include=['number']).columns
df1_numeric = df1[n]
scaler1 = StandardScaler()
df1_scaled_array = scaler1.fit_transform(df1_numeric)
df1_scaled = pd.DataFrame(df1_scaled_array, columns=n)
df1_scaled

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years
0,-1.714126,-1.462863,-0.882040,-0.341235,-0.411165,1.788917,-0.147412
1,-1.714048,0.971113,1.220423,1.713436,-0.411165,1.788917,-0.147412
2,-1.695488,2.593763,1.420657,0.343655,-0.411165,1.788917,-0.147412
3,-1.712775,0.971113,0.439508,1.028546,-0.411165,1.788917,-0.147412
4,-1.712042,-1.462863,-0.841993,-0.341235,-0.411165,1.788917,-0.147412
...,...,...,...,...,...,...,...
14994,1.630149,-1.462863,-1.002181,-0.341235,-0.411165,1.788917,-0.147412
14995,1.630265,-1.462863,-0.821970,-0.341235,-0.411165,1.788917,-0.147412
14996,1.630496,-1.462863,-1.162368,-0.341235,-0.411165,1.788917,-0.147412
14997,1.630574,1.782438,1.580845,0.343655,-0.411165,1.788917,-0.147412
14998,1.630689,-1.462863,-0.862016,-0.341235,-0.411165,1.788917,-0.147412

In [5]:
#task---minmax scaler
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
df1 = pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv ')
n = df1.select_dtypes(include=['number']).columns
df1_numeric = df1[n]
scaler1 = MinMaxScaler()
df1_scaled_array = scaler1.fit_transform(df1_numeric)
df1_scaled = pd.DataFrame(df1_scaled_array, columns=n)
df1_scaled

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years
0,0.000000,0.0,0.285047,0.125,0.0,1.0,0.0
1,0.000020,0.6,0.775701,0.500,0.0,1.0,0.0
2,0.004888,1.0,0.822430,0.250,0.0,1.0,0.0
3,0.000354,0.6,0.593458,0.375,0.0,1.0,0.0
4,0.000546,0.0,0.294393,0.125,0.0,1.0,0.0
...,...,...,...,...,...,...,...
14994,0.877090,0.0,0.257009,0.125,0.0,1.0,0.0
14995,0.877120,0.0,0.299065,0.125,0.0,1.0,0.0
14996,0.877181,0.0,0.219626,0.125,0.0,1.0,0.0
14997,0.877201,0.8,0.859813,0.250,0.0,1.0,0.0
14998,0.877232,0.0,0.289720,0.125,0.0,1.0,0.0

In [6]:
#task---normalizer scaler
import pandas as pd
from sklearn.preprocessing import  Normalizer
df1 = pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv ')
n = df1.select_dtypes(include=['number']).columns
df1_numeric = df1[n]
scaler1 =  Normalizer()
df1_scaled_array = scaler1.fit_transform(df1_numeric)
df1_scaled = pd.DataFrame(df1_scaled_array, columns=n)
df1_scaled

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years
0,0.987963,0.001970,0.154646,0.002955,0.0,0.000985,0.0
1,0.967630,0.004814,0.252258,0.005777,0.0,0.000963,0.0
2,0.983643,0.004634,0.180048,0.002648,0.0,0.000662,0.0
3,0.977670,0.004709,0.210039,0.004709,0.0,0.000942,0.0
4,0.988868,0.001871,0.148751,0.002807,0.0,0.000936,0.0
...,...,...,...,...,...,...,...
14994,0.999999,0.000023,0.001722,0.000034,0.0,0.000011,0.0
14995,0.999998,0.000023,0.001825,0.000034,0.0,0.000011,0.0
14996,0.999999,0.000023,0.001631,0.000034,0.0,0.000011,0.0
14997,0.999995,0.000068,0.003193,0.000046,0.0,0.000011,0.0
14998,0.999998,0.000023,0.001802,0.000034,0.0,0.000011,0.0