<a href="https://colab.research.google.com/github/hipparagiaishwarya2130-lang/datascience/blob/main/Feature_Scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

FEATURE SCALING-

In [21]:
#Standardisation
import pandas as pd
from sklearn.preprocessing import StandardScaler
df=pd.DataFrame({'grams':[2,3,4,5],'price':[200,500,800,1200]})
ss=StandardScaler()
#fit-learning data,calculating mean,devitaion done by fit
#transform-tranforming or reflecting it to original data
df_scaled=ss.fit_transform(df)
df_scaled

array([[-1.34164079, -1.28390102],
       [-0.4472136 , -0.47301616],
       [ 0.4472136 ,  0.33786869],
       [ 1.34164079,  1.41904849]])

In [22]:
df2=pd.DataFrame(df_scaled,columns=df.columns)
df2

      grams     price
0 -1.341641 -1.283901
1 -0.447214 -0.473016
2  0.447214  0.337869
3  1.341641  1.419048

In [23]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
df1=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')
ss1=StandardScaler()
n= df1.select_dtypes(include=['number']).columns
df1_numeric=df1[n]
df_scaled1=ss1.fit_transform(df1_numeric)
df_scaled1=pd.DataFrame(df_scaled1,columns=df1_numeric.columns)
df_scaled1

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years
0,-1.714126,-1.462863,-0.882040,-0.341235,-0.411165,1.788917,-0.147412
1,-1.714048,0.971113,1.220423,1.713436,-0.411165,1.788917,-0.147412
2,-1.695488,2.593763,1.420657,0.343655,-0.411165,1.788917,-0.147412
3,-1.712775,0.971113,0.439508,1.028546,-0.411165,1.788917,-0.147412
4,-1.712042,-1.462863,-0.841993,-0.341235,-0.411165,1.788917,-0.147412
...,...,...,...,...,...,...,...
14994,1.630149,-1.462863,-1.002181,-0.341235,-0.411165,1.788917,-0.147412
14995,1.630265,-1.462863,-0.821970,-0.341235,-0.411165,1.788917,-0.147412
14996,1.630496,-1.462863,-1.162368,-0.341235,-0.411165,1.788917,-0.147412
14997,1.630574,1.782438,1.580845,0.343655,-0.411165,1.788917,-0.147412
14998,1.630689,-1.462863,-0.862016,-0.341235,-0.411165,1.788917,-0.147412